src/com/sheepit/client/standalone/swing/activity/Settings.java

I noticed a few situations when the start button would be enabled or disabled at the wrong times. The changes I made should correct the following issues:
1. If you type your username and then paste password from the clipboard, the start button will remain disabled despite both the username and passwords being filled. This is because pasting does not trigger the `keyTyped` event. To fix this I simply moved the `checkDisplaySaveButton` call to the `keyReleased` event, which is called by pasting and regular typing.
2. When the client initially starts, the start button is enabled even if the username or password field is empty. To fix this I added a call to `checkDisplaySaveButton` before the button was added to the content pane.

Fix start button enabling/disabling

---

src/com/sheepit/client/standalone/GuiSwing.java
src/com/sheepit/client/standalone/swing/activity/Settings.java
src/com/sheepit/client/standalone/swing/activity/Working.java

The lack of progress on a flexible layout has been holding up pull requests #23 and #29, as well as just generally annoying me whenever I use the client, so I decided to do it myself.
The layout looks more or less the same as it did before, but it now adjusts based on the content and the size of the window. I have not been able to test how either GPU options or last rendered frame display affect the layout, however they *should* properly follow the layout.
Probably Closes #25

Implemented flexible layout for swing

---

README.md

Cleaned up some odd wording, consolidated website link into Overview section, and spelled out how to use the dev server.
Looks a bit neater to me; I've never understood having a section just for the website link when it can be easily linked near the top of the file. As usual, if you don't like any of the changes, let me know.

Clean up README language

---

src/com/sheepit/client/os/FreeBSD.java

I noticed that the client didn't start after a certain uptime of the FreeBSD machine. I was able to trace it back to an indefinite wait in the FreeBSD class, which was caused by two waitFor().
After the dmesg output reaches a certain size, the output buffer of the process fills up and waits for it to be read. Of course, it doesn't get read and the processes deadlock.
After further review I determined that the waitFor() calls are unnesseary and the code works fine without it.

fixed infinite wait on too large dmesg output

---

src/com/sheepit/client/standalone/Worker.java

if a cache_dir is given as command line argument and it does not exist it will try to create it with it parents

create cache dir if not exists

---

src/com/sheepit/client/standalone/text/CLIInputActionHandler.java

The "status" cli commands outputs "running" and "will exit after the current frame" were swapped.

Fixed status output

---

src/com/sheepit/client/Utils.java

fixes 
```
net.lingala.zip4j.exception.ZipException: net.lingala.zip4j.exception.ZipException: java.lang.IllegalArgumentException: Negative time
at net.lingala.zip4j.unzip.Unzip.initExtractFile(Unzip.java:163)
at net.lingala.zip4j.unzip.Unzip.initExtractAll(Unzip.java:83)
at net.lingala.zip4j.unzip.Unzip.extractAll(Unzip.java:73)
at net.lingala.zip4j.core.ZipFile.extractAll(ZipFile.java:488)
```
by instructing zip4j to ignore the modified date while extracting files.
ref: https://www.sheepit-renderfarm.com/forum/viewtopic.php?f=5&t=1142

fix ZipException: java.lang.IllegalArgumentException: Negative time

---

src/com/sheepit/client/standalone/GuiSwing.java

This PR uses a JSrollPane as root pane, instead of the previous JPanel, which is now the JScrollPane's child.
This should (provisionally) fix #149 .

make the GUI scrollable when needed

---

src/com/sheepit/client/SettingsLoader.java

When passed as inline parameters, memory is expressed as MB. However, when passed in a config file, memory was expressed as KB. This created confusion among users.
This does break backwards compatibility, so merge with caution.
Ideally, a unit could be added to the parameter such as '1000000K' = '1000M' = '1G', making the default unit whatever it was before, but I'll save this for a future PR.

Make config file loader take ram in MB for consistency

---

src/com/sheepit/proxy/Proxy.java

In later versions of JDK, non-standard HTTP methods are disallowed to prevent arbitrarily long request strings for security purposes (see: https://bugs.openjdk.java.net/browse/JDK-7016595 ). To correct this, X-HTTP-Method-Override is used to allow the CONNECT method to work properly.
This workaround requires the receiving server to correctly understand POST and X-HTTP-Method-Override, and cleaner workarounds do exist, however our server understands these properly so this workaround should be acceptable.

Corrected HTTP Method Usage for Later JDK Versions

---

src/com/sheepit/client/Utils.java

Fixed a typo where, when displaying a time (elapsed time, remaining time), the time is shown without any spaces between the hours, minutes and seconds (ie 1h24min4s). 
The correct format should be 1h 24min 4s.

fix: typo when displaying time strings

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/standalone/Worker.java

The upload process was not correctly queuing completed frames. As a result, a new job request was only triggered when the previous frame upload was finished (not immediately by using the existing background upload process).
Fixed the sync/async detection routine to ensure that handle the frames according to server specs. 
Additionally, in agreement with @laurent-clouet, removed the _-max-uploading-job_ inline option. Therefore, background upload is now enabled by default.

Fix: background frame uploads not queuing properly

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/Gui.java
src/com/sheepit/client/Job.java
src/com/sheepit/client/standalone/GuiSwing.java
src/com/sheepit/client/standalone/GuiText.java
src/com/sheepit/client/standalone/GuiTextOneLine.java
src/com/sheepit/client/standalone/swing/activity/Working.java

With the new feature (#209) that unlocks the upload of frames in the background, is sometimes difficult to know the status of the client. Questions like how many uploads are waiting in the queue or what's the size of the upload queue are not evident for the user.
This PR contains the following improvements to the background upload process:
- New information added to all the clients (GUI, text and oneLine) to show the number of frames waiting to be uploaded and the total size of the upload.
- Different messages to inform if the frame is going to be sent synchronously or is queued.
- A new message indicating when the client is not taking new jobs while the upload queue is full. This is happening as soon as the upload queue reaches 3 files.
- GUI UI additional information example:
- Text UI …

feature: improve user information on queued uploads

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/Gui.java
src/com/sheepit/client/standalone/GuiSwing.java
src/com/sheepit/client/standalone/GuiText.java
src/com/sheepit/client/standalone/GuiTextOneLine.java
src/com/sheepit/client/standalone/swing/activity/Working.java

This PR improves the overall process of manually pausing the client. Main changes in the client:
- Changed the labels of the _pause_ button to make the action more explicit
- Changed the status label:
- While the client is still finishing the current job
- Once the client is paused and stops retrieving new jobs
The three (GUI, text and OneLine) UIs have been adapted to the new capabilities.

Improve the pause button screen workflow

---

.idea/gradle.xml
src/com/sheepit/client/Client.java
src/com/sheepit/client/standalone/swing/activity/Working.java

This PR improves the overall client application exit process. With the addition of background uploads, it's difficult for the user to know the impact of closing the client.
The added feature includes:
- Changed the name of the exit button to just _Exit_
- When the user clicks the _Exit_ button, they can now choose between two different exit strategies:
- Close the client once all the frames have been uploaded to the server or;
- Cancel all the jobs (current + queued for upload) and close the client immediately.
- When the client is waiting for background uploads to close, the Exit button indicates the number of pending jobs to finish.
- Additional improvements in the internal wait/upload/job detection process.
Screenshots:

Feature: improve the application exit-button process

---

build.gradle
src/com/sheepit/client/Server.java

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
at com.sheepit.client.Utils.md5(Utils.java:83)
at com.sheepit.client.Configuration.cleanDirectory(Configuration.java:205)
at com.sheepit.client.Configuration.cleanWorkingDirectory(Configuration.java:185)
at com.sheepit.client.Client.run(Client.java:113)
at com.sheepit.client.standalone.GuiSwing$ThreadClient.run(GuiSwing.java:425)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
... 5 more
```
JAXB APIs are considered to be a part of Java EE and …

Fix JAXB NoClassDefFoundError on Java 9+

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/standalone/GuiSwing.java

There was a racing condition between the queue full message and **any** error message where the later are overwritten by the former. Modified so the error messages are always shown in the client, regardless of the client status.

Fix: racing condition with error messages when the queue is full

---

src/com/sheepit/client/Configuration.java
src/com/sheepit/client/Job.java
src/com/sheepit/client/SettingsLoader.java
src/com/sheepit/client/hardware/gpu/GPUDevice.java
src/com/sheepit/client/hardware/gpu/GPULister.java
src/com/sheepit/client/hardware/gpu/nvidia/Nvidia.java
src/com/sheepit/client/hardware/gpu/opencl/OpenCL.java
src/com/sheepit/client/standalone/Worker.java
src/com/sheepit/client/standalone/swing/activity/Settings.java

This feature allows the user to configure the default GPU render bucket size (aka render tile size).
Interestingly, the fastest render time for CPU is the slowest on the GPU. This due to the GPU only being able to render one tile at a time, so it doesn't benefit from more tiles, but for being able to calculate more information and minimise the transfers between the GPU and the main CPU/memory.
Depending on the GPU, the maximum render bucket size will be 512x512 pixel on CUDA GPUs or 2048x2048 pixel on OPENCL ones (yes, AMD cards really love huge render bucket sizes!!!). The minimum size remains in 32x32 pixel for both GPU and CPU.
The configuration can be done via the Settings screen in the GUI or thru the _-renderbucket-size_ option in the command line.
Screenshot:

Allow the user to configure the GPU render bucket size 

---

src/com/sheepit/client/Client.java

All messages that pause the client execution because the server now follow the pattern "_Error detail_. Will try again at hh:mm".
Examples:
- Cannot connect to the server. Please check your connectivity. Will try again at 01:03
- The server is overloaded and cannot allocate a job. Will try again at 23:17
- The server is under maintenance and cannot allocate a job. Will try again at 07:09
- Bad answer from the server. Will try again at 15:34
- No job available. Will try again at 21:41

Improve waiting messages to show the time of the next retry.

---

src/com/sheepit/client/standalone/swing/activity/Working.java

When a rendered frame cannot be read, the following Java IIOException is showed on the screen or console:
_JavaException when failing to generate thumbnail in SWING client:: (v6.1714) Working::showLastRender() exception javax.imageio.IIOException: Can't read input file! javax.imageio.IIOException: Can't read input file! at javax.imageio.ImageIO.read(Unknown Source) at com.sheepit.client.standalone.swing.activity.Working.showLastRender(Working.java:372) at com.sheepit.client.standalone.swing.activity.Working.setRenderedFrame(Working.java:352) at com.sheepit.client.standalone.GuiSwing.AddFrameRendered(GuiSwing.java:231) at com.sheepit.client.Client.confirmJob(Client.java:830) at com.sheepit.client.Client.senderLoop(Client.java:471) at com.sheepit.client.Client$1.run(Client.java:132) at …

Fix: ugly JavaException when error generating thumbnail in GUI

---

src/com/sheepit/client/Client.java

The existing model implements random time between 10 and 30 minutes when a "no job" response is received. 
The new algorithm will introduce five new incremental steps. If a "no job" response is received, the client will start with a five minutes wait and will increment the waiting time to 8, 12 15 and 20 minutes with every consecutive "no job" reply from the server. After successfully receiving a new job, the waiting time resets to 5 minutes.

Optimise the retries algorithm for the "no job" server response

---

src/com/sheepit/client/Log.java

This not a definitive fix but a proper workaround to ensure the app is not getting randomly frozen when the upload queue is full.
There is a race condition in the way the app execution snapshots are managed. We will review/improve the whole snapshots process but in the meanwhile, this should keep the client from getting frozen.

Fix: app randomly hangs when the upload queue is full

---

src/com/sheepit/client/os/FreeBSD.java
src/com/sheepit/client/os/Linux.java
src/com/sheepit/client/os/Mac.java
src/com/sheepit/client/os/OS.java
src/com/sheepit/client/os/Windows.java
src/com/sheepit/client/standalone/swing/activity/Settings.java

A couple of bugs fixed with this PR:
1. In *nix-based OS, the priority is set using the _nice_ tool, but the Settings window allows you to define the priority even if the tool is non-existent. The Settings window now remove the _Priority_ slider if the tool is not available in the system.
2. The routine to detect if the user in the OS session user has enough rights to increase the priority of the client was returning always true. With this PR, the routine checks two things: a) that the user has enough rights to increase the priority (root and sudo's) via _id_ command and; b) that the _nice_ tool exists.

Fix: functionality to set the client priority not working properly

---

src/com/sheepit/client/Server.java

According to [Let's Encrypt Certificate Compatibility](https://letsencrypt.org/docs/certificate-compatibility/), Identrust's CA root certificates (CN = DST Root CA X3 / O = Digital Signature Trust Co.) are valid from Java 8u101 onwards. 
Currently, the .exe SheepIt client is running with an embedded Java11 JRE and Java8 is the minimum accepted release for our .jar versions.
This PR removes the certificate bypass existing in client versions <= 6.1725.0.

Fix: remove SSL certificate bypass

---

src/com/sheepit/client/Client.java

When an error is raised and the client hasn't allocated any job (ie FermeException produced when the scheduler cannot allocate a job to the client), the sendError method is producing an Exception and the error report is not sent.

Fix: error report not sent when no job allocated

---

src/com/sheepit/client/Client.java

In case of error, the app waits five minutes to request a new job. There are three exceptions to this rule: the `RENDERER_CRASHED`, `RENDERER_KILLED_BY_USER` and `RENDERER_KILLED_BY_SERVER` errors, where the client requests a new job immediately. 
This PR adds the `RENDERER_KILLED_BY_USER_OVER_TIME` error to the no-wait list.

Remove the 5 minutes wait for the RENDERER_KILLED_BY_USER_OVER_TIME

---

src/com/sheepit/client/Configuration.java
src/com/sheepit/client/SettingsLoader.java
src/com/sheepit/client/standalone/Worker.java
src/com/sheepit/client/standalone/swing/activity/Settings.java
src/com/sheepit/client/standalone/swing/activity/Working.java

This PR adds a new configuration option (_Minimise to SysTray_) to the Settings screen. The existing
`--no-systray` parameter still exists and, if present, overwrites the value stored in the configuration file.
Screenshot:

Feature: minimize to SysTray option on the settings screen

---

src/com/sheepit/client/Job.java

As the value of the `askForRendererKill` flag is set right after the return of the killing process, under some particular memory and system load circumstances, a race condition occurs and the main thread (reading the Blender output) closes the process faster than the `process.destroy()` returns the control to the Timer thread. 
If that condition occurs, the `isAskForRendererKill()` check returns false (the flag hasn't been set to _true_ in the separate thread) and the execution continues with the frame output check (that doesn't exist as the rendering process was interrupted). The final outcome is a wrong _NO_FILE_OUTPUT_ error instead of the proper _RENDERER_KILLED_BY_USER_OVER_TIME_.
The fix has been setting the `askForRendererKill` flag to true before the process is destroyed. If the …

Fix: Job killed by time limit is wrongly catalogued as NO_FILE_OUTPUT

---

src/com/sheepit/client/Client.java

In some exceptions and controlled app flows, the log checkpoint is not cleared before creating a new checkpoint and the information remains in memory during all the app execution.

Fix: free memory from unused log checkpoints

---

src/com/sheepit/client/Server.java

Ensure that the error logs sent to the server include any server response not specifically handled by the client.

Fix: include any error response from server in error logs

---

src/com/sheepit/client/Server.java

The HTTPSendFile was adding an "image/" string to the proper file MimeType, rendering the MimeType invalid and not being included in the HTTP header.

Fix: HTTPSendFile doesn't send a valid MimeType header to server

---

src/com/sheepit/client/Gui.java
src/com/sheepit/client/Job.java
src/com/sheepit/client/standalone/GuiSwing.java
src/com/sheepit/client/standalone/GuiText.java
src/com/sheepit/client/standalone/GuiTextOneLine.java

The text UI gets quite messy during the render process, as it takes at least one extra text line per rendering second. This PR fixes that issue and also shows an ASCII bar to show the render progress.
In addition, the rendering progress is more accurate as is based in the tile processed, not only the ETA provided by Blender.
- OneLine UI screenshot:
- Text UI screenshot:
The rendering progress is also shown in the GUI in the form _Rendering 45%_.

Feature: in text UIs, show render progress in one line

---

src/com/sheepit/client/Client.java

If a generic RENDERER_KILLED error is triggered in the client, the app is not sending any error to the server and therefore the frame being processed is not reset on the server. This behaviour can cause zombie frames (the server thinks that are being rendered by the client but the process was killed). 
This PR fixes that problem by sending the frame to be reset to the server along with the error information.

Fix: RENDERER_KILLED error sends a frame reset to server

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/Log.java
src/com/sheepit/client/Server.java

If an error occurs when uploading completed jobs from the upload queue, the app sends an error to the server but doesn't include the frame that needs to be reset in the payload. This behaviour can cause zombie frames (the server thinks that are being rendered by the client but the process was killed).
This PR fixes that problem by sending the frame to be reset to the server along with the error information.
Additionally, the client now correlates all the actions happening in the upload process with the proper checkpoint initially associated with the job, creating a single-aggregated error log from the job allocation to the triggered error (the upload queue is running in a different thread and the log information might be mixed among different threads).

Fix: Send reset signal to server on job upload error

---

src/com/sheepit/client/SettingsLoader.java
src/com/sheepit/client/standalone/Worker.java

The `-compute method` argument doesn't produce any effect on the app. 
The following config-file + `-compute-method` + `-gpu` combinations have been tested:
```
config	-compute-method    -gpu      output    RESULT
NIL     NIL                 NIL      CPU       +OK
NIL     CPU                 NIL      CPU       +OK
NIL     GPU                 NIL      Error     +OK
NIL     GPU                 valid    GPU       +OK
NIL     NIL                 valid    GPU       +OK
NIL     CPU_GPU             NIL      Error     +OK
NIL     CPU_GPU             valid    CPU/GPU   +OK
CPU     NIL                 NIL      CPU       +OK
CPU     NIL                 valid    GPU       +OK
CPU     CPU                 NIL      CPU       +OK
CPU     GPU                 NIL      Error     +OK
CPU     GPU …
```

Fix: -compute-method argument doesn't work

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/Server.java

When the kill instruction is received from the server it checks three things before the signal is propagated:
1) There is a valid instance of client object (`client != null`) **AND**;
2) There is a valid job allocated to the client (`client.getRenderingJob() != null`) **AND**;
3) there is a valid rendering process being executed (`client.getRenderingJob().getProcessRender().getProcess() != null`)
The current glitch occurs when a kill signal is received from the server and the job is allocated to the client (points **1** and **2**) but the rendering process (**3**) hasn't yet started (ie, the scene is being downloaded). When that situation occurs (and probably in some others as well), the client might enter an endless loop where the client is sending the allocated job as part of the …

Fix: download not cancelled by server kill (possible root cause of kill loops)

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/Error.java
src/com/sheepit/client/Server.java

Add a new error code to handle HTTP 413 errors if returned from the SheepIt Shepherds. The error should be considered catastrophic as there is no way of recovering from an app viewpoint (configuration must be changed in the server to increase the maximum body size).
As part of the PR, the error will be logged and sent back to the server with a new error code `IMAGE_TOO_LONG` to allow SheepIt admins to track the error.

Feature: check for HTTP 413 (Entity too large) errors

---

src/com/sheepit/client/Client.java

In addition to RENDERER_KILLED_BY_SERVER and RENDERER_KILLED_BY_ USER_OVERTIME, add the user interruption (RENDERER_KILLED_BY_USER) to the reasons to cancel the download and not retry.

Fix: add RENDERER_KILLED_BY_USER to download checks

---

src/com/sheepit/client/Client.java

To automatically detect the MimeType of the file being sent to the server, the app makes a call to the `Files.probeContentType` method. ProbeContentType uses the file extension to assign the correct MimeType. As files with error log sent to the server don't have any extension (they have a farm_XXXXXXXXXXXXX pattern) the probeContentType method generates a NULL MimeType.
As logs are plain text files, this PR adds the .txt extension to the log files generated to generate the proper MimeType.

Fix: NULL MimeType when sending files without extension

---

src/com/sheepit/client/Job.java
src/com/sheepit/client/SettingsLoader.java
src/com/sheepit/client/hardware/cpu/CPU.java
src/com/sheepit/client/hardware/gpu/GPU.java
src/com/sheepit/client/hardware/gpu/GPUDevice.java
src/com/sheepit/client/standalone/Worker.java
src/com/sheepit/client/standalone/swing/activity/Settings.java

The `-renderbucket-size` option is not applied if the app runs in an environment with no configuration file. This PR fixes the bug and also implements all possible argument/config file combinations.

Fix: -renderbucket-size value not applied to GPU render

---

src/com/sheepit/client/standalone/Worker.java

I see a great benefit in informing the user that a public key is also an option for the `-password` parameter in the client itself aswell, not just from the website.

Include public key as password in help

---

src/com/sheepit/client/Server.java
src/com/sheepit/client/Utils.java

A user reported that his upload would continually fail with the following error:
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull stacktrace java.lang.IllegalArgumentException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull
at okhttp3.MediaType$Companion.parse(MediaType.kt)
at okhttp3.MediaType.parse(MediaType.kt)
at com.sheepit.client.Server.HTTPSendFile(Server.java:497)
at com.sheepit.client.Client.confirmJob(Client.java:875)
at com.sheepit.client.Client.run(Client.java:358)
at com.sheepit.client.standalone.GuiSwing$ThreadClient.run(GuiSwing.java:412)
```
`Files.probeContentType` can return null if the content …

Fix failed MimeType detection

---

src/com/sheepit/client/Server.java

When an HTTP error is raised in the job allocation process, the current algorithm triggers a NullPointerException that interrupts the program execution and closes gracefully. This PR includes additional checks and also catches all possible exceptions in the process.

Fix: NullPointerException triggered when http error in job allocation

---

src/com/sheepit/client/Server.java

this was a copy+paste error at some point, judging by the other error logging around it.

fix broken log message

---

src/com/sheepit/client/Job.java

When we compute openCL frames, blender engine(s) logs on the console output, the remaining time of a frame.
But we were hiding the result for now. (Why?)
TODO: test under multiple O.S. and with different Blender engines version
Fix for me (under linux and using opencl) #279

 restore missing time remaining time in UI with openCL

---

src/com/sheepit/client/Job.java

Fix: Make initial Test/Power Frames ignore user max render time setting

---

.idea/client-luis.iml
src/com/sheepit/client/Client.java
src/com/sheepit/client/Gui.java
src/com/sheepit/client/Server.java
src/com/sheepit/client/TransferStats.java
src/com/sheepit/client/Utils.java
src/com/sheepit/client/standalone/GuiSwing.java
src/com/sheepit/client/standalone/GuiText.java
src/com/sheepit/client/standalone/GuiTextOneLine.java
src/com/sheepit/client/standalone/swing/activity/Working.java

Adds the total bytes downloaded and uploaded in the current session as well as the average data transfer rate for both UL/DL. The information is not added to the 1-line UI as the line will take 150+ characters in the screen.
The way of calculating the session arithmetic mean is:
`number of bytes transferred in the session / seconds spent transferring the data`
Downloads and uploads data/time are calculated separately.
Screenshot:
As requested by @Raimund58

Feature: add session data consumption information in GUI/text UIs

---

src/com/sheepit/client/Client.java
src/com/sheepit/client/Configuration.java
src/com/sheepit/client/Job.java
src/com/sheepit/client/Server.java
src/com/sheepit/client/standalone/Worker.java

This feature is especially relevant for users with several clients running simultaneously within the same computer (computers running several GPUs or any combination of GPUs + CPUs) or multiple computers running in a network. The feature allows the user to specify a shared downloads directory via the new _-shared-zip_ client option. All the clients using that option will download the binaries and new scenes once and will share them across the clients.
**How it works?**
The first client downloading a binary or scene will save the file in the directory specified in _-shared-zip_. The rest of the clients using the same shared directory will wait until the file has been downloaded. Once the file has been downloaded, it will be ready for the rest of the clients.
This feature is especially …

Feature: support for shared downloads directory
