src/com/sheepit/client/Job.java
=> Wrap project name in double quotes

src/com/sheepit/client/standalone/GuiText.java, src/com/sheepit/client/standalone/GuiTextOneLine.java
the current render time and remaining render time were switched
=> fix the display of current render time and remaining time

src/com/sheepit/client/standalone/swing/activity/Settings.java
For details, see https://www.sheepit-renderfarm.com/forum/viewtopic.php?f=9&t=1010
=> Prevent computer name / host name from being deleted between sessions.

protocol.txt
Nothing really notable here, just minor cleanup of wording and spelling. Also spell out what path the configuration request should go to.
=> Minor protocol.txt improvements

src/com/sheepit/client/Job.java
When sending Ctrl+C to the terminal it also get's sent to all subprocesses e.g. also the render process.
The java program handles Ctrl+C but the renderer quits on Ctrl+C
This script causes the renderer to ignore Ctrl+C.
See https://cdn.discordapp.com/attachments/301912419368697856/452458122087497728/sheepit-client.jar for a jar that includes my changes.
=> Ignore Ctrl+C in render process. Fixes #81

src/com/sheepit/client/Error.java
Corrected and clarified the 'MISSING RENDER' error case.
=> clarification of error message

src/com/sheepit/client/Client.java, src/com/sheepit/client/Job.java
As of now, the ant build fails with 2 errors. Each has been fixed in a separate commit.
=> Fix Ant Build

README.md
I was going to submit this to the forum, but then I remembered I could submit a PR for it :D
=> Fix grammar and consistency of README

src/com/sheepit/proxy/Proxy.java
Added a shortened URL string to reduce line wrap on proxy stdout.
Also removed excessive ------- and redundant information which appeared on every line.
=> Cosmetic change to reduce line wrap on proxy stdout

build.gradle, src/com/sheepit/client/os/windows/WinProcess.java, src/com/sheepit/client/standalone/Worker.java
This shouldn't have any side effects.
=> Resolve compiler warnings

src/com/sheepit/client/Client.java
Add three new status messages:
- Uploading frame, including rendered frame size.
- Stopping the client and;
- Disconnecting from SheepIt servers
to keep the user better informed about the actions performed by the client.
Additionally, amended some existing messages to make them more user friendly, while maintaining the existing technical logs.
Those changes are fully compatible with existing client and required for new UI.
=> Improve status messages

src/com/sheepit/client/Client.java
Fixed a couple of glitches happening when a network error occurs while uploading a finished job. 
When a network error occurs while submitting a completed frame, the _confirmJob_ method returns the execution flow in the middle of the method, not setting the proper flags and not removing the image from the hard drive. As a result, the process that checks the number of concurrent jobs calculates an invalid number of jobs in flight and pauses new job requests.
Also, the upload queue counter was not reducing the number of queued projects when a network error occurred while uploading a finished frame.
=> fix: ghost project is created when a job upload fails

src/com/sheepit/client/standalone/ListGpuParameterHandler.java, src/com/sheepit/client/standalone/Worker.java
Review all error messages in application launch.
=> Review and improve error messages

src/com/sheepit/client/Client.java, src/com/sheepit/client/Job.java
For admins internal use. It creates a summary with all the relevant information to better analyse the issue.
=> Include a header in error log summarised info for easier analysis

src/com/sheepit/client/standalone/GuiText.java, src/com/sheepit/client/standalone/GuiTextOneLine.java
Add the timestamp to the screen output to easily check if the client is active.
TS implemented in both _text_ and _oneLine_ text UIs.
=> Feature: add timestamp to screen output in text UIs

src/com/sheepit/client/standalone/swing/activity/Settings.java
This PR will nicely integrate the version of the app in the right bottom part of the SheepIt logo. 
Screenshot:
=> Feature: include the app version in Settings screen

src/com/sheepit/client/Server.java, src/com/sheepit/client/SettingsLoader.java, src/com/sheepit/client/Utils.java, src/com/sheepit/client/network/Proxy.java, src/com/sheepit/client/standalone/GuiSwing.java, src/com/sheepit/client/standalone/swing/activity/Settings.java
Remove from several classes the unnecessary imports.
=> Refactor: remove unnecessary imports

src/com/sheepit/client/Client.java
In the current version, if the rendering process of any of the test frames fails, the client enters in a dead loop of download > extraction > render > error > upload error > repeat. With this PR, If the render of any of the initial test frames fails, the client will stop the execution and will display the proper message to the user.
As requested by @Tehrasha
=> Fix: Display error & stop retrying in case of test frames render error

src/com/sheepit/client/standalone/Worker.java
=> Feature: Make -hostname a cmd line variable

README.md
=> Updates usage command in README.md
